### ISSUE TITLE
Help with domoticz

### ISSUE THREAD

**Issue by merluxx** [khoih-prog/AsyncHTTPRequest_Generic#33] opened 2022-05-15 15:10 UTC
hello I try to send sensor values ​​on a home automation server (Domoticz) but always receive a bad request response while the same url in a browser works. Could you help me ?
My code :
```
static bool requestOpenResult;
  if (reqdom.readyState() == readyStateUnsent || reqdom.readyState() == readyStateDone)
  {
    requestOpenResult = reqdom.open("GET", "http://192.168.1.252:8080/json.htm?type=command&param=udevice&idx=308&nvalue=0&svalue=21.0");

    if (requestOpenResult)
    {
      // Only send() if open() returns true, or crash
      reqdom.send();
    }
    else
    {
      Serial.println(F("Can't send bad request"));
    }
  }
  else
  {
    Serial.println(F("Can't send request"));
  }
```
Debug :
```
16:57:00.829 -> Starting AsyncHTTPRequest_ESP using 
16:57:03.427 -> [AHTTP] setDebug( on ) version AsyncHTTPRequest_Generic v1.8.1
16:57:03.427 -> [AHTTP] setDebug( on ) version AsyncHTTPRequest_Generic v1.8.1
16:57:03.427 -> [AHTTP] open( GET , url = http://192.168.1.252:8080/json.htm?type=command&param=udevice&idx=308&nvalue=0&svalue=21.0
16:57:03.460 -> [AHTTP] _parseURL(): scheme+host HTTP:// 192.168.1.252
16:57:03.460 -> [AHTTP] _parseURL(): port+path+query 8080 /json.htm ?type=command&param=udevice&idx=308&nvalue=0&svalue=21.0
16:57:03.460 -> [AHTTP] open: conneting to hostname = 192.168.1.252:8080
16:57:03.460 -> [AHTTP] _connect()
16:57:03.460 -> [AHTTP] send()
16:57:03.460 -> [AHTTP] _buildRequest()
16:57:03.460 -> [AHTTP] _HTTPmethod = 0
16:57:03.494 -> [AHTTP] GET  /json.htm ?type=command&param=udevice&idx=308&nvalue=0&svalue=21.0  HTTP/1.1
16:57:03.494 -> 
16:57:03.494 -> [AHTTP] host : 192.168.1.252:8080 
16:57:03.494 -> 
16:57:03.494 -> [AHTTP] _send(), _request->available = 107
16:57:03.494 -> [AHTTP] !connected
16:57:03.532 -> [AHTTP] _onConnect handler
16:57:03.532 -> [AHTTP] _setReadyState : 1
16:57:03.532 -> [AHTTP] _send(), _request->available = 107
16:57:03.532 -> [AHTTP] *send 107
16:57:03.532 -> [AHTTP] _onData handler HTTP/1.1 400 Bad Request
16:57:03.532 -> Content-Length: 89
16:57:03.532 -> Content-Type: text/html;charset=UTF-8
16:57:03.532 -> 
16:57:03.532 -> <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html> , len = 176
16:57:03.532 -> [AHTTP] _collectHeaders()
16:57:03.532 -> [AHTTP] xbuf::readString: Reserved size =  27
16:57:03.565 -> [AHTTP] xbuf::readString: Reserved size =  21
16:57:03.565 -> [AHTTP] xbuf::readString: Reserved size =  40
16:57:03.565 -> [AHTTP] xbuf::readString: Reserved size =  3
16:57:03.565 -> [AHTTP] _setReadyState : 2
16:57:03.565 -> [AHTTP] _setReadyState : 3
16:57:03.565 -> [AHTTP] *all data received - no disconnect
16:57:03.565 -> [AHTTP] _setReadyState : 4
16:57:03.565 -> 
16:57:03.565 -> **************reqdomCB*****************
16:57:03.565 -> [AHTTP] responseText()
16:57:03.565 -> [AHTTP] xbuf::readString: Reserved size =  90
16:57:03.599 -> [AHTTP] responseText(char) <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html> , avail = 89
16:57:03.599 -> <html><head><title>Bad Request</title></head><body><h1>400 Bad Request</h1></body></html>
16:57:03.599 -> **************reqdomCB*****************
16:57:03.599 -> [AHTTP] 
16:57:03.599 -> _onDisconnect handler
16:57:03.599 -> [AHTTP] _HTTPcode =  400
```

**Comment by khoih-prog** [comment] 2022-05-18 15:13
Sorry I have no way to duplicate your issue as I don't use domoticz. Not everything accessible by `Chrome` or full-fledged WebBrowsers can access by simple HTTP Request.

The response was `400 Bad Request`, as you could see, must give you some clue.

You can post and ask for support on `Domoticz` site or Forum.

I'm closing this issue now as this is not a bug of the library.

Good Luck,

**Closed by khoih-prog** 2022-05-18 15:13 UTC
