### ISSUE TITLE
LiquidCrystal_I2C lcd not printing correctly in requestCB async method

### ISSUE THREAD

**Issue by rajes53** [khoih-prog/AsyncHTTPRequest_Generic#30] opened 2022-04-20 02:59 UTC
When i am printing something on a 16x2 LCD in sendRequest() method it is working correctly but when i am printing inside aysnc method requestCB() lcd not printing correctly even lcd.clear() is also not clearing characters on screen.

I am using Esp32 board + LiquidCrystal_I2C to print http request data on LCD. It is printing something different char on screen.

#include<LiquidCrystal_I2C.h>
LiquidCrystal_I2C lcd(0x27, 16, 2);

`void requestCB(void* optParm, AsyncHTTPRequest* request, int readyState) 
{
  (void) optParm;
  
  if (readyState == readyStateDone) 
  {
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print("SUCCESS HTTP");

    Serial.println(F("\n**************************************"));
    Serial.println(request->responseText());
    Serial.println(F("**************************************"));
    
    request->setDebug(false);
  }
}`

Other methods are printing correctly on LCD. Any

**Comment by khoih-prog** [comment] 2022-04-20 03:13
It's possible the lcd functions of **LiquidCrystal_I2C** library create some conflicts, some bug or excessive delay (by using slow I2C) and not compatible to be used inside callback function `requestCB`. Post an issue there to understand why.

It's better to set a flag or write to a buffer inside the `requestCB`, then use a timer to check the flag and call lcd functions.

This is not a bug of the library, so I'm closing now.

Good Luck,

**Closed by khoih-prog** 2022-04-20 03:13 UTC
