### ISSUE TITLE
Exception cause 28 in open request

### ISSUE THREAD

**Issue by dirkvranckaert** [khoih-prog/AsyncHTTPRequest_Generic#48] opened 2022-11-18 06:14 UTC
From my production devices from time to time I gather a crash with exception cause 28 (LoadProhibitedCause, so basically a NPE) with the final traces within this library.

```
Restart reason: 2
Exception cause: 28

0x40206b9d: AsyncHTTPRequest::open(char const*, char const*) at /Users/xyz/Documents/Arduino/libraries/AsyncHTTPRequest_Generic/src/AsyncHTTPRequest_Impl_Generic.h:556
 (inlined by) AsyncHTTPRequest::open(char const*, char const*) at /Users/xyz/Documents/Arduino/libraries/AsyncHTTPRequest_Generic/src/AsyncHTTPRequest_Impl_Generic.h:490
```

After checking the library locally the error is on this line:
<img width="628" alt="Screenshot 2022-11-18 at 07 09 51" src="https://user-images.githubusercontent.com/4660794/202633120-dd004b7e-e240-4c16-9bb2-3c296d26df2e.png">

My initialisation code for the open call looks like this:

```
AsyncHTTPRequest request;
const String HOST = "http://api.myserver.com";
const String BASE_URL = "/v1";

void executeCall() {
  request.setDebug(DEBUG);
  request.onReadyStateChange(handlePostResult);
  String urlMethod = "ping";
  String url = BASE_URL + "/" + urlMethod;
  String fullUrl = HOST + url;
  request.open("POST", fullUrl.c_str());
}
```

The error is not appearing often, just from time to time. I also cannot reproduce so far locally. But I wonder if sometimes the `c_str()` could give an empty/false result making the library crash...?!

The error has been installed like this because my production builds are generated with arduino-cli:
```shell
arduino-cli lib install --git-url https://github.com/khoih-prog/AsyncHTTPRequest_Generic.git
```
The version is `1.9.1`.

Any other ideas we might be able to investigate?
This is happening in production, I could roll out a new build with a new version, but result won't be seen very fast off course...

**Comment by khoih-prog** [comment] 2022-11-18 21:24
Hi @dirkvranckaert 

> The error is not appearing often, just from time to time. I also cannot reproduce so far locally

With this kink of issue, it's really hard for anybody to nail down the culprit.

Can you try the **latest** library version, or even check and change **your code**,  because the `NullPointerException` (NPE) can also be created from any other portion of your code.

Remember the infamous `BSOD` ? Sometimes, in extreme cases, you have to live with that, and write code to recover from random crashes to minimize bad consequences.

If you're using ESP32/ESP8266, use `ESP Exception Decoder` to hopefully isolate the bad code. If not using ESPs, you can port the code to ESP, run to see if random crashes still happen, then use use `ESP Exception Decoder`.

Also without any minimal info, such as board, core, libraries' versions, your full code or [**MRE**](https://stackoverflow.com/help/minimal-reproducible-example), I don't think anyone can help you out here.

Anyway, I'm closing the issue now, and only reopen when, hopefully, you can prove that this is a bug, which can make this library much better.

Good Luck,

**Closed by khoih-prog** 2022-11-18 21:24 UTC
